### PR TITLE
Added async, for, and loop to special keyword handling in parse_attributes

### LINKED ISSUE #130: Rust keywords in attribute list
When compiling a HTML form containing `label`s with `for` attributes, I get the error
```
error: expected `>`
  --> app/src/views/login.rs:18:24
   |
18 |                 <label for="username">Username:</label>
   |                        ^^^

error: aborting due to previous error
```

My current workaround is to use capitalisation to avoid the parser treating the attribute as a keyword (since Rust is case sensitive and HTML is not). For example:
```
<label For="username">Username:</label>
```

There are four [Rust keywords](https://doc.rust-lang.org/reference/keywords.html) that are also [valid HTML attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes): `async`, `for`, `loop`, and `type`. There already seems to be special handling for `type` in `parse_attributes`:  https://github.com/chinedufn/percy/blob/66e1dcd4ed94733160ec694dfcb2021be3d7503a/crates/html-macro/src/tag.rs#L131-L144

I think the remaining three keywords just need to be added there. I will create a pull request for this change.

### PR DESCRIPTION
**Pull request by FinnStokes**
Closes #130.

### CODE REVIEW

**Comment by chinedufn** [comment]
Thanks!

One small request - mind adding 3 more tiny tests here?

https://github.com/chinedufn/percy/blob/e4d86f3b5f6596f38bbaef5ba942760be48b9ce4/crates/html-macro-test/src/lib.rs#L211-L215

**Comment by FinnStokes** [comment]
Good point. I've added the requested tests.

**Comment by chinedufn** [comment]
Perfect - thanks!

**Comment by chinedufn** [comment]
Published as `virtual-dom-rs 6.9.10` or `html-macro 0.1.7`!

**Pull request merged**
